title: Erika Senft Miller
description: A conceptual performance artist actively exploring and embracing the power of movement through rigorous academic research, a careful pattern of creative productivity, and in-depth multimedia integration and documentation of her work.
baseurl: "/"
url: ""

collections:
  pages:
    output: true
    permalink: /:title/ 
  upload:
    output: true
  projects:
    output: true
    permalink: /:collection/:name
  press:
    output:    

kramdown:  
  parse_block_html: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"