backend:
  name: git-gateway
  branch: master

display_url: https://erikasenftmiller.com
media_folder: "assets/images/upcoming"

collections:
  - label: "Upcoming"
    name: "upcoming"
    folder: "_upcoming"
    label_singular: "Upcoming Happening"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "upcoming"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "string"}
      - {label: "Time", name: "time", widget: "string"}
      - {label: "Site", name: "site", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: "false"}
