backend:
  name:             git-gateway
  branch:           master

display_url:        https://erikasenftmiller.com
media_folder:       "assets/images/upcoming"

collections:
  - label:          "Upcoming Projects"
    name:           "upcoming"
    folder:         "_upcoming"
    label_singular: "Upcoming Project"
    create:         true
    editor:
      preview:      false
    fields:
      - {
        label:      "Layout",
        name:       "layout",
        widget:     "hidden",
        default:    "upcoming"
        }
      - {
        label:      "Title",
        name:       "title",
        widget:     "string"
        }
      - {
        lable:      "Event Date",
        name:       "date",
        widget:     "datetime",
        }
      - {
        label:      "Site / Location",
        name:       "site",
        widget:     "string"
        }
      - {
        label:      "Site / Location Details",
        name:       "location",
        widget:     "string",
        required:   false
        }
      - {
        label:      "Image",
        name:       "image",
        widget:     "image",
        required:   false
        }
      - {
        label:      "Body",
        name:       "body",
        widget:     "markdown"
        }
