backend:
  name: git-gateway
  branch: master

display_url: https://erikasenftmiller.com
media_folder: "assets/images/upcoming"

collections:
  - label: "Upcoming Projects"
    name: "upcoming"
    folder: "_upcoming"
    label_singular: "Upcoming Project"
    create: true
    editor:
      preview: false
    fields:
      - {
        label: "Layout",
        name: "layout",
        widget: "hidden",
        default: "upcoming"
        }
      - {
        label: "Title",
        name: "title",
        widget: "string"
        }
      - {
        lable: "Date",
        name: "date",
        widget: "datetime",
        }
      - {
        label: "Site",
        name: "site",
        widget: "string"
        }
      - {
        label: "Location Details",
        name: "location",
        widget: "string"
        }
      - {
        label: "Body",
        name: "body",
        widget: "markdown"
        }
